In [24]:
import keras
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential, Model
from keras.layers import Dropout,Flatten,Dense,Conv2D,MaxPooling2D
from keras import backend as k
from keras.callbacks import ModelCheckpoint,LearningRateScheduler,TensorBoard,EarlyStopping
from keras.models import load_model
import numpy as np

In [25]:

#hdd_csv="/media/sharath/Elements/RSF/training_data/all_data.csv"
#hdd_label_csv="/media/sharath/Elements/RSF/training_data/labels.csv"

hdd_csv="/media/data/poc-machine-seis/txt_data/data.csv"
hdd_label_csv="/media/data/poc-machine-seis/txt_data/labels.csv"

#hdd_train_csv="/media/sharath/Elements/RSF/test_data/test_data.csv"
#hdd_train_label_csv="/media/sharath/Elements/RSF/test_data/test_labels.csv"


batch_size=10
num_classes=2
epochs=4

data_rows,data_cols=1126,648
train_samples=10
test_samples=4
x=np.loadtxt(hdd_csv)
y=np.loadtxt(hdd_label_csv)


#x_test=np.loadtxt(hdd_train_csv)
#y_test=np.loadtxt(hdd_train_label_csv)
print(x.shape)


(198, 729648)


In [26]:
print(y.shape)

(198,)


shuffle the data. currently unshuffled!

In [27]:
train_samples=150
test_samples=48
tp=zip(x,y)
ll=list(tp)
import random
random.shuffle(ll)
x_train=np.zeros((train_samples,data_rows*data_cols))
y_train=np.zeros((train_samples,1))
x_test=np.zeros((test_samples,data_rows*data_cols))
y_test=np.zeros((test_samples,1))
 
ik=0
for lk in ll[:train_samples]:
    x_train[ik]=lk[0]
    y_train[ik]=lk[1]
    ik=ik+1

ik=0
for lk in ll[train_samples:]:
    x_test[ik]=lk[0]
    y_test[ik]=lk[1]
    ik=ik+1


print(x_train.shape)
print(x_test.shape)

(150, 729648)
(48, 729648)


import random
tp_train=(x_train,y_train)
tp_test=(x_test,y_test)
l=list(tp_train)
random.shuffle(l)
x2_train=np.zeros(x_train.shape)
y2_train=np.zeros(y_train.shape)
for ll in l:
    

reshape to (10,4501,648,1)


In [28]:


x_train=x_train.reshape(train_samples,data_rows,data_cols,1)
x_test=x_test.reshape(test_samples,data_rows,data_cols,1)
y_train=keras.utils.to_categorical(y_train,num_classes)
y_test=keras.utils.to_categorical(y_test,num_classes)
print(y_train)
print(y_test)

[[0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 

build network

In [29]:
model=Sequential()
model.add(Conv2D(16,kernel_size=(3,3)
                 ,activation='relu'
                 ,input_shape=(data_rows,data_cols,1)))

model.add(Conv2D(32,kernel_size=(5,5)
                   ,activation='relu'))
model.add(MaxPooling2D(pool_size=(4,4)))
model.add(Conv2D(16,kernel_size=(3,3)
                   ,activation='relu'))
model.add(Conv2D(32,kernel_size=(5,5)
                   ,activation='relu'))
model.add(MaxPooling2D(pool_size=(4,4)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(32,activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(num_classes,activation='softmax'))
model.compile(loss=keras.losses.categorical_crossentropy,
             optimizer=keras.optimizers.Adadelta()
             ,metrics=['accuracy'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_13 (Conv2D)           (None, 1124, 646, 16)     160       
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 1120, 642, 32)     12832     
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 280, 160, 32)      0         
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 278, 158, 16)      4624      
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 274, 154, 32)      12832     
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 68, 38, 32)        0         
_________________________________________________________________
dropout_7 (Dropout)          (None, 68, 38, 32)        0         
__________

training the model

In [30]:
batch_size=4
epochs=10
model.fit(x_train,y_train
         ,batch_size=batch_size
         ,epochs=epochs
         ,verbose=1
         ,validation_data=(x_test,y_test))
score=model.evaluate(x_test,y_test,verbose=1)
print('Test loss: ',score[0])
print('Test accuracy: ',score[1])

Train on 150 samples, validate on 48 samples
Epoch 1/10
150/150 [==============================] - 15s 98ms/step - loss: 1.5986 - acc: 0.8533 - val_loss: 8.8510e-05 - val_acc: 1.0000
Epoch 2/10
150/150 [==============================] - 14s 92ms/step - loss: 1.9018e-04 - acc: 1.0000 - val_loss: 1.5279e-05 - val_acc: 1.0000
Epoch 3/10
150/150 [==============================] - 14s 92ms/step - loss: 0.0139 - acc: 0.9933 - val_loss: 1.8721e-05 - val_acc: 1.0000
Epoch 4/10
150/150 [==============================] - 14s 92ms/step - loss: 2.2525e-04 - acc: 1.0000 - val_loss: 1.2666e-06 - val_acc: 1.0000
Epoch 5/10
150/150 [==============================] - 14s 92ms/step - loss: 7.3184e-05 - acc: 1.0000 - val_loss: 1.8875e-07 - val_acc: 1.0000
Epoch 6/10
150/150 [==============================] - 14s 92ms/step - loss: 8.4364e-06 - acc: 1.0000 - val_loss: 1.1921e-07 - val_acc: 1.0000
Epoch 7/10
150/150 [==============================] - 14s 91ms/step - loss: 1.9286e-05 - acc: 1.0000 - val_loss

save model

In [ ]:
model.save('tagging_model.h5')
print("Saved model")

load the model to check

In [ ]:
print("Loading model")
loaded_model=load_model('tagging_model.h5')
print("Done Loading model")

In [31]:
hdd_field_csv="/media/data/poc-machine-seis/field_test_data/data.csv"
hdd_field_label="/media/data/poc-machine-seis/field_test_data/labels.csv"
field_samples=198
field_data=np.loadtxt(hdd_field_csv)
field_label=np.loadtxt(hdd_field_label)
field_data=field_data.reshape(field_samples,data_rows*data_cols)



In [32]:
f_pred=np.array(field_data[160])

In [33]:
field_p=field_data[160].reshape(1,data_rows,data_cols,1)
field_p.shape

(1, 1126, 648, 1)

In [34]:
loaded_model.predict_classes(field_p)

array([1])

In [35]:
field_p=field_data.reshape(field_samples,data_rows,data_cols,1)
field_p.shape

(198, 1126, 648, 1)

In [36]:
preds=loaded_model.predict_classes(field_p)

In [37]:
preds.shape

(198,)

In [38]:
field_label.shape

(198,)

In [41]:
print(preds[0])
print(field_label[0])

0
0.0


In [42]:
preds==field_label

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,